// @generated by
//     __             _____     _                 ___ ___
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
// v0.12.9                         -- www.JsonSchema42.org
//
/**
* @description The description of OpenAPI v3.0.x documents, as defined by https://spec.openapis.org/oas/v3.0.3
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#}
*/
export type SchemaDocument = (
{
"openapi": Openapi,
"info": PropertiesInfo,
"externalDocs"?: PropertiesExternalDocs,
"servers"?: PropertiesServers,
"security"?: PropertiesSecurity,
"tags"?: PropertiesTags,
"paths": PropertiesPaths,
"components"?: PropertiesComponents,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Reference}
*/
export type Reference = (
{
"$ref": any,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info}
*/
export type DefinitionsInfo = (
{
"title": InfoTitle,
"description"?: InfoDescription,
"termsOfService"?: TermsOfService,
"contact"?: InfoContact,
"license"?: InfoLicense,
"version": Version,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Contact}
*/
export type DefinitionsContact = (
{
"name"?: ContactName,
"url"?: ContactUrl,
"email"?: Email,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/License}
*/
export type DefinitionsLicense = (
{
"name": LicenseName,
"url"?: LicenseUrl,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Server}
*/
export type DefinitionsServer = (
{
"url": ServerUrl,
"description"?: ServerDescription,
"variables"?: Variables,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ServerVariable}
*/
export type ServerVariable = (
{
"enum"?: ServerVariableEnum,
"default": ServerVariableDefault,
"description"?: ServerVariableDescription,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components}
*/
export type DefinitionsComponents = (
{
"schemas"?: Schemas,
"responses"?: ComponentsResponses,
"parameters"?: ComponentsParameters,
"examples"?: ComponentsExamples,
"requestBodies"?: RequestBodies,
"headers"?: ComponentsHeaders,
"securitySchemes"?: SecuritySchemes,
"links"?: ComponentsLinks,
"callbacks"?: ComponentsCallbacks,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema}
*/
export type DefinitionsSchema = (
{
"title"?: SchemaTitle,
"multipleOf"?: MultipleOf,
"maximum"?: Maximum,
"exclusiveMaximum"?: ExclusiveMaximum,
"minimum"?: Minimum,
"exclusiveMinimum"?: ExclusiveMinimum,
"maxLength"?: MaxLength,
"minLength"?: MinLength,
"pattern"?: Pattern,
"maxItems"?: MaxItems,
"minItems"?: MinItems,
"uniqueItems"?: UniqueItems,
"maxProperties"?: MaxProperties,
"minProperties"?: MinProperties,
"required"?: SchemaRequired,
"enum"?: SchemaEnum,
"type"?: SchemaType,
"not"?: SchemaNot,
"allOf"?: AllOf,
"oneOf"?: OneOf,
"anyOf"?: AnyOf,
"items"?: PropertiesSchemaItems,
"properties"?: Properties,
"additionalProperties"?: PropertiesSchemaAdditionalProperties,
"description"?: SchemaDescription,
"format"?: Format,
"default"?: SchemaDefault,
"nullable"?: Nullable,
"discriminator"?: SchemaDiscriminator,
"readOnly"?: ReadOnly,
"writeOnly"?: WriteOnly,
"example"?: SchemaExample,
"externalDocs"?: SchemaExternalDocs,
"deprecated"?: SchemaDeprecated,
"xml"?: SchemaXml,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Discriminator}
*/
export type DefinitionsDiscriminator = (
{
"propertyName": PropertyName,
"mapping"?: Mapping,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML}
*/
export type DefinitionsXml = (
{
"name"?: XmlName,
"namespace"?: Namespace,
"prefix"?: Prefix,
"attribute"?: Attribute,
"wrapped"?: Wrapped,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response}
*/
export type Response = (
{
"description": ResponseDescription,
"headers"?: ResponseHeaders,
"content"?: ResponseContent,
"links"?: ResponseLinks,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType}
*/
export type MediaType = (
{
"schema"?: MediaTypeSchema,
"example"?: MediaTypeExample,
"examples"?: MediaTypeExamples,
"encoding"?: MediaTypeEncoding,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Example}
*/
export type DefinitionsExample = (
{
"summary"?: ExampleSummary,
"description"?: ExampleDescription,
"value"?: Value,
"externalValue"?: ExternalValue,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header}
*/
export type Header = (
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema": HeaderSchema,
"content"?: HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema"?: HeaderSchema,
"content": HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Paths}
*/
export type DefinitionsPaths = (
{
[
name: string
]: PathsAdditionalProperties |
PatternProperties |
PathsX
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem}
*/
export type PathItem = (
{
"$ref"?: PathItemRef,
"summary"?: PathItemSummary,
"description"?: PathItemDescription,
"servers"?: PathItemServers,
"parameters"?: PathItemParameters,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation}
*/
export type Operation = (
{
"tags"?: OperationTags,
"summary"?: OperationSummary,
"description"?: OperationDescription,
"externalDocs"?: OperationExternalDocs,
"operationId"?: OperationOperationId,
"parameters"?: OperationParameters,
"requestBody"?: OperationRequestBody,
"responses": OperationResponses,
"callbacks"?: OperationCallbacks,
"deprecated"?: OperationDeprecated,
"security"?: OperationSecurity,
"servers"?: OperationServers,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses}
*/
export type DefinitionsResponses = (
{
"default"?: ResponsesDefault,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityRequirement}
*/
export type SecurityRequirement = (
{
[
name: string
]: SecurityRequirementAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Tag}
*/
export type Tag = (
{
"name": TagName,
"description"?: TagDescription,
"externalDocs"?: TagExternalDocs,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ExternalDocumentation}
*/
export type ExternalDocumentation = (
{
"description"?: ExternalDocumentationDescription,
"url": ExternalDocumentationUrl,
}
);
/**
* @description Example and examples are mutually exclusive
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ExampleXORExamples}
*/
export type ExampleXorExamples = (unknown);
/**
* @description Schema and content are mutually exclusive, at least one is required
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent}
*/
export type SchemaXorContent = (
(unknown)
|
(unknown)
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter}
*/
export type Parameter = (
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema": ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content": ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("path"),
"description"?: ParameterDescription,
"required": (true),
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("matrix" |
"label" |
"simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("query"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("header"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("cookie"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
);
/**
* @description Parameter location
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation}
*/
export type ParameterLocation = (
ParameterLocation0
|
ParameterLocation1
|
ParameterLocation2
|
ParameterLocation3
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/RequestBody}
*/
export type DefinitionsRequestBody = (
{
"description"?: RequestBodyDescription,
"content": RequestBodyContent,
"required"?: RequestBodyRequired,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityScheme}
*/
export type SecurityScheme = (
SecurityScheme0
|
(
{
"scheme": (string),
"bearerFormat"?: BearerFormat,
"description"?: HttpSecuritySchemeDescription,
"type": HttpSecuritySchemeType,
}
)
|
(
{
"scheme": (string),
"bearerFormat"?: BearerFormat,
"description"?: HttpSecuritySchemeDescription,
"type": HttpSecuritySchemeType,
}
)
|
SecurityScheme2
|
SecurityScheme3
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/APIKeySecurityScheme}
*/
export type ApiKeySecurityScheme = (
{
"type": ApiKeySecuritySchemeType,
"name": ApiKeySecuritySchemeName,
"in": ApiKeySecuritySchemeIn,
"description"?: ApiKeySecuritySchemeDescription,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme}
*/
export type HttpSecurityScheme = (
(
{
"scheme": (string),
"bearerFormat"?: BearerFormat,
"description"?: HttpSecuritySchemeDescription,
"type": HttpSecuritySchemeType,
}
)
|
(
{
"scheme": (string),
"bearerFormat"?: BearerFormat,
"description"?: HttpSecuritySchemeDescription,
"type": HttpSecuritySchemeType,
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuth2SecurityScheme}
*/
export type Oauth2SecurityScheme = (
{
"type": Oauth2SecuritySchemeType,
"flows": Flows,
"description"?: Oauth2SecuritySchemeDescription,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OpenIdConnectSecurityScheme}
*/
export type OpenIdConnectSecurityScheme = (
{
"type": OpenIdConnectSecuritySchemeType,
"openIdConnectUrl": OpenIdConnectUrl,
"description"?: OpenIdConnectSecuritySchemeDescription,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuthFlows}
*/
export type OauthFlows = (
{
"implicit"?: Implicit,
"password"?: Password,
"clientCredentials"?: ClientCredentials,
"authorizationCode"?: AuthorizationCode,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ImplicitOAuthFlow}
*/
export type ImplicitOauthFlow = (
{
"authorizationUrl": ImplicitOauthFlowAuthorizationUrl,
"refreshUrl"?: ImplicitOauthFlowRefreshUrl,
"scopes": ImplicitOauthFlowScopes,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PasswordOAuthFlow}
*/
export type PasswordOauthFlow = (
{
"tokenUrl": PasswordOauthFlowTokenUrl,
"refreshUrl"?: PasswordOauthFlowRefreshUrl,
"scopes": PasswordOauthFlowScopes,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ClientCredentialsFlow}
*/
export type ClientCredentialsFlow = (
{
"tokenUrl": ClientCredentialsFlowTokenUrl,
"refreshUrl"?: ClientCredentialsFlowRefreshUrl,
"scopes": ClientCredentialsFlowScopes,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow}
*/
export type AuthorizationCodeOauthFlow = (
{
"authorizationUrl": AuthorizationCodeOauthFlowAuthorizationUrl,
"tokenUrl": AuthorizationCodeOauthFlowTokenUrl,
"refreshUrl"?: AuthorizationCodeOauthFlowRefreshUrl,
"scopes": AuthorizationCodeOauthFlowScopes,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link}
*/
export type Link = (
{
"operationId"?: LinkOperationId,
"operationRef"?: OperationRef,
"parameters"?: LinkParameters,
"requestBody"?: LinkRequestBody,
"description"?: LinkDescription,
"server"?: LinkServer,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Callback}
*/
export type Callback = (
{
[
name: string
]: CallbackAdditionalProperties |
CallbackX
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding}
*/
export type DefinitionsEncoding = (
{
"contentType"?: ContentType,
"headers"?: EncodingHeaders,
"style"?: EncodingStyle,
"explode"?: EncodingExplode,
"allowReserved"?: EncodingAllowReserved,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/openapi}
*/
export type Openapi = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/info}
*/
export type PropertiesInfo = (DefinitionsInfo);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/externalDocs}
*/
export type PropertiesExternalDocs = (ExternalDocumentation);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/servers}
*/
export type PropertiesServers = (
[
...(PropertiesServersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/security}
*/
export type PropertiesSecurity = (
[
...(PropertiesSecurityItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/tags}
*/
export type PropertiesTags = (
[
...(PropertiesTagsItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/paths}
*/
export type PropertiesPaths = (DefinitionsPaths);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/components}
*/
export type PropertiesComponents = (DefinitionsComponents);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/additionalProperties}
*/
export type AdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/patternProperties/^x-}
*/
export type PatternPropertiesX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Reference/patternProperties/^\$ref$}
*/
export type ReferenceRef = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/properties/title}
*/
export type InfoTitle = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/properties/description}
*/
export type InfoDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/properties/termsOfService}
*/
export type TermsOfService = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/properties/contact}
*/
export type InfoContact = (DefinitionsContact);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/properties/license}
*/
export type InfoLicense = (DefinitionsLicense);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/properties/version}
*/
export type Version = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/additionalProperties}
*/
export type InfoAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Info/patternProperties/^x-}
*/
export type InfoX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Contact/properties/name}
*/
export type ContactName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Contact/properties/url}
*/
export type ContactUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Contact/properties/email}
*/
export type Email = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Contact/additionalProperties}
*/
export type ContactAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Contact/patternProperties/^x-}
*/
export type ContactX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/License/properties/name}
*/
export type LicenseName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/License/properties/url}
*/
export type LicenseUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/License/additionalProperties}
*/
export type LicenseAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/License/patternProperties/^x-}
*/
export type LicenseX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Server/properties/url}
*/
export type ServerUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Server/properties/description}
*/
export type ServerDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Server/properties/variables}
*/
export type Variables = (
{
[
name: string
]: VariablesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Server/additionalProperties}
*/
export type ServerAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Server/patternProperties/^x-}
*/
export type ServerX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ServerVariable/properties/enum}
*/
export type ServerVariableEnum = (
[
...(ServerVariableEnumItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ServerVariable/properties/default}
*/
export type ServerVariableDefault = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ServerVariable/properties/description}
*/
export type ServerVariableDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ServerVariable/additionalProperties}
*/
export type ServerVariableAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ServerVariable/patternProperties/^x-}
*/
export type ServerVariableX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/schemas}
*/
export type Schemas = (
{
[
name: string
]: SchemasAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/responses}
*/
export type ComponentsResponses = (
{
[
name: string
]: ResponsesAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/parameters}
*/
export type ComponentsParameters = (
{
[
name: string
]: ParametersAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/examples}
*/
export type ComponentsExamples = (
{
[
name: string
]: ExamplesAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/requestBodies}
*/
export type RequestBodies = (
{
[
name: string
]: RequestBodiesAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/headers}
*/
export type ComponentsHeaders = (
{
[
name: string
]: HeadersAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/securitySchemes}
*/
export type SecuritySchemes = (
{
[
name: string
]: SecuritySchemesAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/links}
*/
export type ComponentsLinks = (
{
[
name: string
]: LinksAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/callbacks}
*/
export type ComponentsCallbacks = (
{
[
name: string
]: CallbacksAZAZ09
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/additionalProperties}
*/
export type ComponentsAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/patternProperties/^x-}
*/
export type ComponentsX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/title}
*/
export type SchemaTitle = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/multipleOf}
*/
export type MultipleOf = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/maximum}
*/
export type Maximum = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/exclusiveMaximum}
*/
export type ExclusiveMaximum = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/minimum}
*/
export type Minimum = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/exclusiveMinimum}
*/
export type ExclusiveMinimum = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/maxLength}
*/
export type MaxLength = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/minLength}
*/
export type MinLength = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/pattern}
*/
export type Pattern = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/maxItems}
*/
export type MaxItems = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/minItems}
*/
export type MinItems = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/uniqueItems}
*/
export type UniqueItems = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/maxProperties}
*/
export type MaxProperties = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/minProperties}
*/
export type MinProperties = (number);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/required}
*/
export type SchemaRequired = (
[
...(RequiredItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/enum}
*/
export type SchemaEnum = (
[
...(SchemaEnumItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/type}
*/
export type SchemaType = ("array" |
"boolean" |
"integer" |
"number" |
"object" |
"string");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/not}
*/
export type SchemaNot = (
Not0
|
Not1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/allOf}
*/
export type AllOf = (
[
...(AllOfItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/oneOf}
*/
export type OneOf = (
[
...(OneOfSchemaItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/anyOf}
*/
export type AnyOf = (
[
...(AnyOfItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/items}
*/
export type PropertiesSchemaItems = (
Items0
|
Items1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/properties}
*/
export type Properties = (
{
[
name: string
]: PropertiesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/additionalProperties}
*/
export type PropertiesSchemaAdditionalProperties = (
Schema0
|
Schema1
|
Schema2
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/description}
*/
export type SchemaDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/format}
*/
export type Format = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/default}
*/
export type SchemaDefault = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/nullable}
*/
export type Nullable = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/discriminator}
*/
export type SchemaDiscriminator = (DefinitionsDiscriminator);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/readOnly}
*/
export type ReadOnly = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/writeOnly}
*/
export type WriteOnly = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/example}
*/
export type SchemaExample = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/externalDocs}
*/
export type SchemaExternalDocs = (ExternalDocumentation);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/deprecated}
*/
export type SchemaDeprecated = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/xml}
*/
export type SchemaXml = (DefinitionsXml);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/additionalProperties}
*/
export type DefinitionsSchemaAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/patternProperties/^x-}
*/
export type SchemaPatternPropertiesX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Discriminator/properties/propertyName}
*/
export type PropertyName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Discriminator/properties/mapping}
*/
export type Mapping = (
{
[
name: string
]: MappingAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML/properties/name}
*/
export type XmlName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML/properties/namespace}
*/
export type Namespace = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML/properties/prefix}
*/
export type Prefix = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML/properties/attribute}
*/
export type Attribute = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML/properties/wrapped}
*/
export type Wrapped = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML/additionalProperties}
*/
export type XmlAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/XML/patternProperties/^x-}
*/
export type XmlX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/description}
*/
export type ResponseDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/headers}
*/
export type ResponseHeaders = (
{
[
name: string
]: HeadersAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/content}
*/
export type ResponseContent = (
{
[
name: string
]: ResponseContentAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/links}
*/
export type ResponseLinks = (
{
[
name: string
]: LinksAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/additionalProperties}
*/
export type ResponseAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/patternProperties/^x-}
*/
export type ResponseX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/schema}
*/
export type MediaTypeSchema = (
SchemaMediaType0
|
SchemaMediaType1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/example}
*/
export type MediaTypeExample = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/examples}
*/
export type MediaTypeExamples = (
{
[
name: string
]: ExamplesMediaTypeAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/encoding}
*/
export type MediaTypeEncoding = (
{
[
name: string
]: MediaTypeEncodingAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/additionalProperties}
*/
export type DefinitionsMediaTypeAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/patternProperties/^x-}
*/
export type MediaTypeX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/allOf/0}
*/
export type AllOfMediaType0 = (ExampleXorExamples);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Example/properties/summary}
*/
export type ExampleSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Example/properties/description}
*/
export type ExampleDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Example/properties/value}
*/
export type Value = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Example/properties/externalValue}
*/
export type ExternalValue = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Example/additionalProperties}
*/
export type ExampleAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Example/patternProperties/^x-}
*/
export type ExampleX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/description}
*/
export type HeaderDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/required}
*/
export type HeaderRequired = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/deprecated}
*/
export type HeaderDeprecated = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/allowEmptyValue}
*/
export type HeaderAllowEmptyValue = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/style}
*/
export type HeaderStyle = ("simple");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/explode}
*/
export type HeaderExplode = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/allowReserved}
*/
export type HeaderAllowReserved = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/schema}
*/
export type HeaderSchema = (
Header0
|
Header1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/content}
*/
export type HeaderContent = (
{
[
name: string
]: HeaderContentAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/example}
*/
export type HeaderExample = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/examples}
*/
export type HeaderExamples = (
{
[
name: string
]: HeaderExamplesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/additionalProperties}
*/
export type HeaderAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/patternProperties/^x-}
*/
export type HeaderX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/allOf/0}
*/
export type HeaderAllOf0 = (ExampleXorExamples);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/allOf/1}
*/
export type HeaderAllOf1 = (SchemaXorContent);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Paths/additionalProperties}
*/
export type PathsAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Paths/patternProperties/^\/}
*/
export type PatternProperties = (PathItem);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Paths/patternProperties/^x-}
*/
export type PathsX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/$ref}
*/
export type PathItemRef = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/summary}
*/
export type PathItemSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/description}
*/
export type PathItemDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/servers}
*/
export type PathItemServers = (
[
...(PathItemServersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/parameters}
*/
export type PathItemParameters = (
[
...(PathItemItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/additionalProperties}
*/
export type PathItemAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/patternProperties/^(get|put|post|delete|options|head|patch|trace)$}
*/
export type GetPutPostDeleteOptionsHeadPatchTrace = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/patternProperties/^x-}
*/
export type PathItemX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/tags}
*/
export type OperationTags = (
[
...(OperationTagsItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/summary}
*/
export type OperationSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/description}
*/
export type OperationDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/externalDocs}
*/
export type OperationExternalDocs = (ExternalDocumentation);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/operationId}
*/
export type OperationOperationId = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/parameters}
*/
export type OperationParameters = (
[
...(ParametersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/requestBody}
*/
export type OperationRequestBody = (
RequestBody0
|
RequestBody1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/responses}
*/
export type OperationResponses = (DefinitionsResponses);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/callbacks}
*/
export type OperationCallbacks = (
{
[
name: string
]: CallbacksAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/deprecated}
*/
export type OperationDeprecated = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/security}
*/
export type OperationSecurity = (
[
...(OperationSecurityItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/servers}
*/
export type OperationServers = (
[
...(OperationServersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/additionalProperties}
*/
export type OperationAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/patternProperties/^x-}
*/
export type OperationX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/properties/default}
*/
export type ResponsesDefault = (
Default0
|
Default1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/additionalProperties}
*/
export type ResponsesAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/patternProperties/^[1-5](?:\d{2}|XX)$}
*/
export type Responses15D2Xx = (
Responses15D2Xx0
|
Responses15D2Xx1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/patternProperties/^x-}
*/
export type ResponsesX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityRequirement/additionalProperties}
*/
export type SecurityRequirementAdditionalProperties = (
[
...(SecurityRequirementItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Tag/properties/name}
*/
export type TagName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Tag/properties/description}
*/
export type TagDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Tag/properties/externalDocs}
*/
export type TagExternalDocs = (ExternalDocumentation);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Tag/additionalProperties}
*/
export type TagAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Tag/patternProperties/^x-}
*/
export type TagX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ExternalDocumentation/properties/description}
*/
export type ExternalDocumentationDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ExternalDocumentation/properties/url}
*/
export type ExternalDocumentationUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ExternalDocumentation/additionalProperties}
*/
export type ExternalDocumentationAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ExternalDocumentation/patternProperties/^x-}
*/
export type ExternalDocumentationX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ExampleXORExamples/not}
*/
export type ExampleXorExamplesNot = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/0}
*/
export type OneOfSchemaXorContent0 = (unknown);
/**
* @description Some properties are not allowed if content is present
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1}
*/
export type OneOfSchemaXorContent1 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/not}
*/
export type DefinitionsSchemaXorContentNot = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/name}
*/
export type ParameterName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/in}
*/
export type ParameterIn = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/description}
*/
export type ParameterDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/required}
*/
export type ParameterRequired = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/deprecated}
*/
export type ParameterDeprecated = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/allowEmptyValue}
*/
export type ParameterAllowEmptyValue = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/style}
*/
export type ParameterStyle = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/explode}
*/
export type ParameterExplode = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/allowReserved}
*/
export type ParameterAllowReserved = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/schema}
*/
export type ParameterSchema = (
Parameter0
|
Parameter1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/content}
*/
export type ParameterContent = (
{
[
name: string
]: ParameterContentAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/example}
*/
export type ParameterExample = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/examples}
*/
export type ParameterExamples = (
{
[
name: string
]: ParameterExamplesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/additionalProperties}
*/
export type ParameterAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/patternProperties/^x-}
*/
export type ParameterX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/allOf/0}
*/
export type ParameterAllOf0 = (ExampleXorExamples);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/allOf/1}
*/
export type ParameterAllOf1 = (SchemaXorContent);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/allOf/2}
*/
export type AllOf2 = (ParameterLocation);
/**
* @description Parameter in path
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/0}
*/
export type ParameterLocation0 = (unknown);
/**
* @description Parameter in query
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/1}
*/
export type ParameterLocation1 = (unknown);
/**
* @description Parameter in header
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/2}
*/
export type ParameterLocation2 = (unknown);
/**
* @description Parameter in cookie
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/3}
*/
export type ParameterLocation3 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/RequestBody/properties/description}
*/
export type RequestBodyDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/RequestBody/properties/content}
*/
export type RequestBodyContent = (
{
[
name: string
]: RequestBodyContentAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/RequestBody/properties/required}
*/
export type RequestBodyRequired = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/RequestBody/additionalProperties}
*/
export type RequestBodyAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/RequestBody/patternProperties/^x-}
*/
export type RequestBodyX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityScheme/oneOf/0}
*/
export type SecurityScheme0 = (ApiKeySecurityScheme);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityScheme/oneOf/1}
*/
export type SecurityScheme1 = (HttpSecurityScheme);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityScheme/oneOf/2}
*/
export type SecurityScheme2 = (Oauth2SecurityScheme);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityScheme/oneOf/3}
*/
export type SecurityScheme3 = (OpenIdConnectSecurityScheme);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/APIKeySecurityScheme/properties/type}
*/
export type ApiKeySecuritySchemeType = ("apiKey");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/APIKeySecurityScheme/properties/name}
*/
export type ApiKeySecuritySchemeName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/APIKeySecurityScheme/properties/in}
*/
export type ApiKeySecuritySchemeIn = ("header" |
"query" |
"cookie");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/APIKeySecurityScheme/properties/description}
*/
export type ApiKeySecuritySchemeDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/APIKeySecurityScheme/additionalProperties}
*/
export type ApiKeySecuritySchemeAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/APIKeySecurityScheme/patternProperties/^x-}
*/
export type ApiKeySecuritySchemeX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/properties/scheme}
*/
export type PropertiesHttpSecuritySchemeScheme = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/properties/bearerFormat}
*/
export type BearerFormat = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/properties/description}
*/
export type HttpSecuritySchemeDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/properties/type}
*/
export type HttpSecuritySchemeType = ("http");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/additionalProperties}
*/
export type HttpSecuritySchemeAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/patternProperties/^x-}
*/
export type HttpSecuritySchemeX = (unknown);
/**
* @description Bearer
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/oneOf/0}
*/
export type HttpSecurityScheme0 = (unknown);
/**
* @description Non Bearer
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/oneOf/1}
*/
export type HttpSecurityScheme1 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuth2SecurityScheme/properties/type}
*/
export type Oauth2SecuritySchemeType = ("oauth2");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuth2SecurityScheme/properties/flows}
*/
export type Flows = (OauthFlows);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuth2SecurityScheme/properties/description}
*/
export type Oauth2SecuritySchemeDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuth2SecurityScheme/additionalProperties}
*/
export type Oauth2SecuritySchemeAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuth2SecurityScheme/patternProperties/^x-}
*/
export type Oauth2SecuritySchemeX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OpenIdConnectSecurityScheme/properties/type}
*/
export type OpenIdConnectSecuritySchemeType = ("openIdConnect");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OpenIdConnectSecurityScheme/properties/openIdConnectUrl}
*/
export type OpenIdConnectUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OpenIdConnectSecurityScheme/properties/description}
*/
export type OpenIdConnectSecuritySchemeDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OpenIdConnectSecurityScheme/additionalProperties}
*/
export type OpenIdConnectSecuritySchemeAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OpenIdConnectSecurityScheme/patternProperties/^x-}
*/
export type OpenIdConnectSecuritySchemeX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuthFlows/properties/implicit}
*/
export type Implicit = (ImplicitOauthFlow);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuthFlows/properties/password}
*/
export type Password = (PasswordOauthFlow);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuthFlows/properties/clientCredentials}
*/
export type ClientCredentials = (ClientCredentialsFlow);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuthFlows/properties/authorizationCode}
*/
export type AuthorizationCode = (AuthorizationCodeOauthFlow);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuthFlows/additionalProperties}
*/
export type OauthFlowsAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/OAuthFlows/patternProperties/^x-}
*/
export type OauthFlowsX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ImplicitOAuthFlow/properties/authorizationUrl}
*/
export type ImplicitOauthFlowAuthorizationUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ImplicitOAuthFlow/properties/refreshUrl}
*/
export type ImplicitOauthFlowRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ImplicitOAuthFlow/properties/scopes}
*/
export type ImplicitOauthFlowScopes = (
{
[
name: string
]: ScopesImplicitOauthFlowAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ImplicitOAuthFlow/additionalProperties}
*/
export type DefinitionsImplicitOauthFlowAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ImplicitOAuthFlow/patternProperties/^x-}
*/
export type ImplicitOauthFlowX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PasswordOAuthFlow/properties/tokenUrl}
*/
export type PasswordOauthFlowTokenUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PasswordOAuthFlow/properties/refreshUrl}
*/
export type PasswordOauthFlowRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PasswordOAuthFlow/properties/scopes}
*/
export type PasswordOauthFlowScopes = (
{
[
name: string
]: ScopesPasswordOauthFlowAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PasswordOAuthFlow/additionalProperties}
*/
export type DefinitionsPasswordOauthFlowAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PasswordOAuthFlow/patternProperties/^x-}
*/
export type PasswordOauthFlowX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ClientCredentialsFlow/properties/tokenUrl}
*/
export type ClientCredentialsFlowTokenUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ClientCredentialsFlow/properties/refreshUrl}
*/
export type ClientCredentialsFlowRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ClientCredentialsFlow/properties/scopes}
*/
export type ClientCredentialsFlowScopes = (
{
[
name: string
]: ScopesClientCredentialsFlowAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ClientCredentialsFlow/additionalProperties}
*/
export type DefinitionsClientCredentialsFlowAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ClientCredentialsFlow/patternProperties/^x-}
*/
export type ClientCredentialsFlowX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow/properties/authorizationUrl}
*/
export type AuthorizationCodeOauthFlowAuthorizationUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow/properties/tokenUrl}
*/
export type AuthorizationCodeOauthFlowTokenUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow/properties/refreshUrl}
*/
export type AuthorizationCodeOauthFlowRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow/properties/scopes}
*/
export type AuthorizationCodeOauthFlowScopes = (
{
[
name: string
]: ScopesAuthorizationCodeOauthFlowAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow/additionalProperties}
*/
export type DefinitionsAuthorizationCodeOauthFlowAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow/patternProperties/^x-}
*/
export type AuthorizationCodeOauthFlowX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/properties/operationId}
*/
export type LinkOperationId = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/properties/operationRef}
*/
export type OperationRef = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/properties/parameters}
*/
export type LinkParameters = (
{
[
name: string
]: ParametersLinkAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/properties/requestBody}
*/
export type LinkRequestBody = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/properties/description}
*/
export type LinkDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/properties/server}
*/
export type LinkServer = (DefinitionsServer);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/additionalProperties}
*/
export type DefinitionsLinkAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/patternProperties/^x-}
*/
export type LinkX = (unknown);
/**
* @description Operation Id and Operation Ref are mutually exclusive
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/not}
*/
export type LinkNot = (
{
"operationId": LinkOperationId,
"operationRef": OperationRef,
"parameters"?: LinkParameters,
"requestBody"?: LinkRequestBody,
"description"?: LinkDescription,
"server"?: LinkServer,
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Callback/additionalProperties}
*/
export type CallbackAdditionalProperties = (PathItem);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Callback/patternProperties/^x-}
*/
export type CallbackX = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/contentType}
*/
export type ContentType = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/headers}
*/
export type EncodingHeaders = (
{
[
name: string
]: HeadersEncodingAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/style}
*/
export type EncodingStyle = ("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/explode}
*/
export type EncodingExplode = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/allowReserved}
*/
export type EncodingAllowReserved = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/additionalProperties}
*/
export type DefinitionsEncodingAdditionalProperties = (never);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/servers/items}
*/
export type PropertiesServersItems = (DefinitionsServer);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/security/items}
*/
export type PropertiesSecurityItems = (SecurityRequirement);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/properties/tags/items}
*/
export type PropertiesTagsItems = (Tag);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Server/properties/variables/additionalProperties}
*/
export type VariablesAdditionalProperties = (ServerVariable);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ServerVariable/properties/enum/items}
*/
export type ServerVariableEnumItems = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/schemas/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type SchemasAZAZ09 = (
Schemas0
|
Schemas1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/responses/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type ResponsesAZAZ09 = (
Responses0
|
Responses1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/parameters/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type ParametersAZAZ09 = (
AZAZ09Parameters0
|
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema": ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content": ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("path"),
"description"?: ParameterDescription,
"required": (true),
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("matrix" |
"label" |
"simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("query"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("header"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("cookie"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/examples/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type ExamplesAZAZ09 = (
AZAZ09Examples0
|
AZAZ09Examples1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/requestBodies/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type RequestBodiesAZAZ09 = (
RequestBodies0
|
RequestBodies1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/headers/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type HeadersAZAZ09 = (
AZAZ09Headers0
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema": HeaderSchema,
"content"?: HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema"?: HeaderSchema,
"content": HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/securitySchemes/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type SecuritySchemesAZAZ09 = (
SecuritySchemes0
|
SecurityScheme0
|
(
{
"scheme": (string),
"bearerFormat"?: BearerFormat,
"description"?: HttpSecuritySchemeDescription,
"type": HttpSecuritySchemeType,
}
)
|
(
{
"scheme": (string),
"bearerFormat"?: BearerFormat,
"description"?: HttpSecuritySchemeDescription,
"type": HttpSecuritySchemeType,
}
)
|
SecurityScheme2
|
SecurityScheme3
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/links/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type LinksAZAZ09 = (
AZAZ09Links0
|
AZAZ09Links1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/callbacks/patternProperties/^[a-zA-Z0-9\.\-_]+$}
*/
export type CallbacksAZAZ09 = (
AZAZ09Callbacks0
|
AZAZ09Callbacks1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/required/items}
*/
export type RequiredItems = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/enum/items}
*/
export type SchemaEnumItems = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/not/oneOf/0}
*/
export type Not0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/not/oneOf/1}
*/
export type Not1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/allOf/items}
*/
export type AllOfItems = (
ItemsAllOf0
|
ItemsAllOf1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/oneOf/items}
*/
export type OneOfSchemaItems = (
OneOf0
|
OneOf1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/anyOf/items}
*/
export type AnyOfItems = (
AnyOf0
|
AnyOf1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/items/oneOf/0}
*/
export type Items0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/items/oneOf/1}
*/
export type Items1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/properties/additionalProperties}
*/
export type PropertiesAdditionalProperties = (
Properties0
|
Properties1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/additionalProperties/oneOf/0}
*/
export type Schema0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/additionalProperties/oneOf/1}
*/
export type Schema1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/additionalProperties/oneOf/2}
*/
export type Schema2 = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Discriminator/properties/mapping/additionalProperties}
*/
export type MappingAdditionalProperties = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/headers/additionalProperties}
*/
export type HeadersAdditionalProperties = (
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema": HeaderSchema,
"content"?: HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema"?: HeaderSchema,
"content": HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
|
ResponseHeaders1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/content/additionalProperties}
*/
export type ResponseContentAdditionalProperties = (MediaType);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/links/additionalProperties}
*/
export type LinksAdditionalProperties = (
ResponseLinks0
|
ResponseLinks1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/schema/oneOf/0}
*/
export type SchemaMediaType0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/schema/oneOf/1}
*/
export type SchemaMediaType1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/examples/additionalProperties}
*/
export type ExamplesMediaTypeAdditionalProperties = (
ExamplesMediaType0
|
ExamplesMediaType1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/encoding/additionalProperties}
*/
export type MediaTypeEncodingAdditionalProperties = (DefinitionsEncoding);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/schema/oneOf/0}
*/
export type Header0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/schema/oneOf/1}
*/
export type Header1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/content/additionalProperties}
*/
export type HeaderContentAdditionalProperties = (MediaType);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/examples/additionalProperties}
*/
export type HeaderExamplesAdditionalProperties = (
HeaderExamples0
|
HeaderExamples1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/servers/items}
*/
export type PathItemServersItems = (DefinitionsServer);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/parameters/items}
*/
export type PathItemItems = (
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema": ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content": ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("path"),
"description"?: ParameterDescription,
"required": (true),
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("matrix" |
"label" |
"simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("query"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("header"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("cookie"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
PathItem1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/tags/items}
*/
export type OperationTagsItems = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/parameters/items}
*/
export type ParametersItems = (
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema": ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ParameterStyle,
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content": ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("path"),
"description"?: ParameterDescription,
"required": (true),
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("matrix" |
"label" |
"simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("query"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("header"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("simple"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
(
{
"name": ParameterName,
"in": ("cookie"),
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"allowEmptyValue"?: ParameterAllowEmptyValue,
"style"?: ("form"),
"explode"?: ParameterExplode,
"allowReserved"?: ParameterAllowReserved,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
"example"?: ParameterExample,
"examples"?: ParameterExamples,
}
)
|
OperationParameters1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/requestBody/oneOf/0}
*/
export type RequestBody0 = (DefinitionsRequestBody);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/requestBody/oneOf/1}
*/
export type RequestBody1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/callbacks/additionalProperties}
*/
export type CallbacksAdditionalProperties = (
OperationCallbacks0
|
OperationCallbacks1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/security/items}
*/
export type OperationSecurityItems = (SecurityRequirement);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/servers/items}
*/
export type OperationServersItems = (DefinitionsServer);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/properties/default/oneOf/0}
*/
export type Default0 = (Response);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/properties/default/oneOf/1}
*/
export type Default1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/patternProperties/^[1-5](?:\d{2}|XX)$/oneOf/0}
*/
export type Responses15D2Xx0 = (Response);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Responses/patternProperties/^[1-5](?:\d{2}|XX)$/oneOf/1}
*/
export type Responses15D2Xx1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SecurityRequirement/additionalProperties/items}
*/
export type SecurityRequirementItems = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/0}
*/
export type AllOfSchemaXorContent0 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/1}
*/
export type AllOfSchemaXorContent1 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/2}
*/
export type SchemaXorContent2 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/3}
*/
export type SchemaXorContent3 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/4}
*/
export type SchemaXorContent4 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/schema/oneOf/0}
*/
export type Parameter0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/schema/oneOf/1}
*/
export type Parameter1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/content/additionalProperties}
*/
export type ParameterContentAdditionalProperties = (MediaType);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/examples/additionalProperties}
*/
export type ParameterExamplesAdditionalProperties = (
ParameterExamples0
|
ParameterExamples1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/0/properties/in}
*/
export type OneOf0ParameterLocationIn = ("path");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/0/properties/style}
*/
export type OneOf0ParameterLocationStyle = ("matrix" |
"label" |
"simple");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/0/properties/required}
*/
export type ParameterLocationRequired = (true);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/1/properties/in}
*/
export type OneOf1ParameterLocationIn = ("query");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/1/properties/style}
*/
export type OneOf1ParameterLocationStyle = ("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/2/properties/in}
*/
export type ParameterLocation2In = ("header");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/2/properties/style}
*/
export type ParameterLocation2Style = ("simple");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/3/properties/in}
*/
export type ParameterLocation3In = ("cookie");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ParameterLocation/oneOf/3/properties/style}
*/
export type ParameterLocation3Style = ("form");
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/RequestBody/properties/content/additionalProperties}
*/
export type RequestBodyContentAdditionalProperties = (MediaType);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/oneOf/0/properties/scheme}
*/
export type OneOf0HttpSecuritySchemeScheme = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/oneOf/1/properties/scheme}
*/
export type OneOf1HttpSecuritySchemeScheme = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/oneOf/1/not}
*/
export type HttpSecuritySchemeNot = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ImplicitOAuthFlow/properties/scopes/additionalProperties}
*/
export type ScopesImplicitOauthFlowAdditionalProperties = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PasswordOAuthFlow/properties/scopes/additionalProperties}
*/
export type ScopesPasswordOauthFlowAdditionalProperties = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/ClientCredentialsFlow/properties/scopes/additionalProperties}
*/
export type ScopesClientCredentialsFlowAdditionalProperties = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/AuthorizationCodeOAuthFlow/properties/scopes/additionalProperties}
*/
export type ScopesAuthorizationCodeOauthFlowAdditionalProperties = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Link/properties/parameters/additionalProperties}
*/
export type ParametersLinkAdditionalProperties = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/headers/additionalProperties}
*/
export type HeadersEncodingAdditionalProperties = (
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema": HeaderSchema,
"content"?: HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"allowEmptyValue"?: HeaderAllowEmptyValue,
"style"?: HeaderStyle,
"explode"?: HeaderExplode,
"allowReserved"?: HeaderAllowReserved,
"schema"?: HeaderSchema,
"content": HeaderContent,
"example"?: HeaderExample,
"examples"?: HeaderExamples,
}
)
|
Encoding1
);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/schemas/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type Schemas0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/schemas/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type Schemas1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/responses/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type Responses0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/responses/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type Responses1 = (Response);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/parameters/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type AZAZ09Parameters0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/parameters/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type AZAZ09Parameters1 = (Parameter);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/examples/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type AZAZ09Examples0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/examples/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type AZAZ09Examples1 = (DefinitionsExample);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/requestBodies/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type RequestBodies0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/requestBodies/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type RequestBodies1 = (DefinitionsRequestBody);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/headers/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type AZAZ09Headers0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/headers/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type AZAZ09Headers1 = (Header);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/securitySchemes/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type SecuritySchemes0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/securitySchemes/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type SecuritySchemes1 = (SecurityScheme);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/links/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type AZAZ09Links0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/links/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type AZAZ09Links1 = (Link);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/callbacks/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/0}
*/
export type AZAZ09Callbacks0 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Components/properties/callbacks/patternProperties/^[a-zA-Z0-9\.\-_]+$/oneOf/1}
*/
export type AZAZ09Callbacks1 = (Callback);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/allOf/items/oneOf/0}
*/
export type ItemsAllOf0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/allOf/items/oneOf/1}
*/
export type ItemsAllOf1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/oneOf/items/oneOf/0}
*/
export type OneOf0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/oneOf/items/oneOf/1}
*/
export type OneOf1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/anyOf/items/oneOf/0}
*/
export type AnyOf0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/anyOf/items/oneOf/1}
*/
export type AnyOf1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/properties/additionalProperties/oneOf/0}
*/
export type Properties0 = (DefinitionsSchema);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema/properties/properties/additionalProperties/oneOf/1}
*/
export type Properties1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/headers/additionalProperties/oneOf/0}
*/
export type ResponseHeaders0 = (Header);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/headers/additionalProperties/oneOf/1}
*/
export type ResponseHeaders1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/links/additionalProperties/oneOf/0}
*/
export type ResponseLinks0 = (Link);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Response/properties/links/additionalProperties/oneOf/1}
*/
export type ResponseLinks1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/examples/additionalProperties/oneOf/0}
*/
export type ExamplesMediaType0 = (DefinitionsExample);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/MediaType/properties/examples/additionalProperties/oneOf/1}
*/
export type ExamplesMediaType1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/examples/additionalProperties/oneOf/0}
*/
export type HeaderExamples0 = (DefinitionsExample);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Header/properties/examples/additionalProperties/oneOf/1}
*/
export type HeaderExamples1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/parameters/items/oneOf/0}
*/
export type PathItem0 = (Parameter);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/PathItem/properties/parameters/items/oneOf/1}
*/
export type PathItem1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/parameters/items/oneOf/0}
*/
export type OperationParameters0 = (Parameter);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/parameters/items/oneOf/1}
*/
export type OperationParameters1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/callbacks/additionalProperties/oneOf/0}
*/
export type OperationCallbacks0 = (Callback);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Operation/properties/callbacks/additionalProperties/oneOf/1}
*/
export type OperationCallbacks1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/0/not}
*/
export type AllOfSchemaXorContentNot = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/1/not}
*/
export type SchemaXorContent1Not = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/2/not}
*/
export type SchemaXorContent2Not = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/3/not}
*/
export type SchemaXorContent3Not = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/SchemaXORContent/oneOf/1/allOf/4/not}
*/
export type SchemaXorContent4Not = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/examples/additionalProperties/oneOf/0}
*/
export type ParameterExamples0 = (DefinitionsExample);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Parameter/properties/examples/additionalProperties/oneOf/1}
*/
export type ParameterExamples1 = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/HTTPSecurityScheme/oneOf/1/properties/scheme/not}
*/
export type SchemeNot = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/headers/additionalProperties/oneOf/0}
*/
export type Encoding0 = (Header);
/**
* @see {@link https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Encoding/properties/headers/additionalProperties/oneOf/1}
*/
export type Encoding1 = (Reference);
