version: "0.2"
words:
  - appsignal
  - AZAZ
  - bindgen
  - Bulthuis
  - camelcase
  - cdylib
  - clippy
  - elmerbulthuis
  - endregion
  - esbenp
  - gloo
  - goodrouter
  - husense
  - itertools
  - mockables
  - Nationaal
  - nawadi
  - ndjson
  - oneshot
  - openapi
  - opentelemetry
  - patsubst
  - prestart
  - Promisable
  - Prospero
  - Quickstart
  - remle
  - repr
  - rlib
  - rollup
  - ryanluker
  - Scheveningen
  - serde
  - Skiffa
  - urlencoding
  - Watersportdiploma
  - welkom
useGitignore: true
files:
  - "**"
enableFiletypes:
  - "*"
ignorePaths:
  - assets/
