#!/bin/sh

cd $(dirname $0)

export NODE_ENV=development
ERROR=0

npm run build --workspaces

for F in $(ls fixtures/specifications/test30.yaml); do
  echo $(basename $F .yaml)
  echo $F

  npx oa42-generator package \
    $F \
    --package-directory .package-npm/specifications/$(basename $F .yaml) \
    --package-name $(basename $F .yaml) \
    --package-version "0.0.0" \

  if [ $? -ne 0 ]; then
    ERROR=1
  fi;

  ( cd .package-npm/specifications/$(basename $F .yaml) ; npm install)
  ( cd .package-npm/specifications/$(basename $F .yaml) ; npm test)

  if [ $? -ne 0 ]; then
    ERROR=1
  fi;

done;

exit $ERROR


