// @generated by
//     __             _____     _                 ___ ___
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
// v0.9.0                          -- www.JsonSchema42.org
// https://spec.openapis.org/oas/3.1/schema/2022-10-07
/**
The description of OpenAPI v3.1.x documents without schema validation, as defined by https://spec.openapis.org/oas/v3.1.0
*/
export type SchemaDocument = (SpecificationExtensions) &
((AnyOf0) |
(AnyOf1) |
(AnyOf2) |
(AnyOf0 & AnyOf1) |
(AnyOf0 & AnyOf2) |
(AnyOf1 & AnyOf2) |
(AnyOf0 & AnyOf1 & AnyOf2)) &
((
{
"openapi": Openapi,
"info": PropertiesInfo,
"jsonSchemaDialect"?: JsonSchemaDialect,
"servers"?: PropertiesServers,
"paths"?: PropertiesPaths,
"webhooks"?: Webhooks,
"components"?: PropertiesComponents,
"security"?: PropertiesSecurity,
"tags"?: PropertiesTags,
"externalDocs"?: PropertiesExternalDocs,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info
export type Info = (SpecificationExtensions) &
((
{
"title": Title,
"summary"?: InfoSummary,
"description"?: InfoDescription,
"termsOfService"?: TermsOfService,
"contact"?: InfoContact,
"license"?: InfoLicense,
"version": Version,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact
export type Contact = (SpecificationExtensions) &
((
{
"name"?: ContactName,
"url"?: ContactUrl,
"email"?: Email,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license
export type License = (SpecificationExtensions) &
((
{
"name": LicenseName,
"identifier"?: Identifier,
"url"?: LicenseUrl,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server
export type Server = (SpecificationExtensions) &
((
{
"url": ServerUrl,
"description"?: ServerDescription,
"variables"?: Variables,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable
export type ServerVariable = (SpecificationExtensions) &
((
{
"enum"?: Enum,
"default": ServerVariableDefault,
"description"?: ServerVariableDescription,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components
export type Components = (SpecificationExtensions) &
((
{
"schemas"?: Schemas,
"responses"?: ComponentsResponses,
"parameters"?: ComponentsParameters,
"examples"?: ComponentsExamples,
"requestBodies"?: RequestBodies,
"headers"?: ComponentsHeaders,
"securitySchemes"?: SecuritySchemes,
"links"?: ComponentsLinks,
"callbacks"?: ComponentsCallbacks,
"pathItems"?: PathItems,
[key: string]: SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItems |
Schemas |
ComponentsResponses |
ComponentsParameters |
ComponentsExamples |
RequestBodies |
ComponentsHeaders |
SecuritySchemes |
ComponentsLinks |
ComponentsCallbacks |
PathItems |
undefined,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/paths
export type Paths = (SpecificationExtensions) &
((
{
[key: string]: PatternProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item
export type PathItem = (SpecificationExtensions) &
((
{
"summary"?: PathItemSummary,
"description"?: PathItemDescription,
"servers"?: PathItemServers,
"parameters"?: PathItemParameters,
"get"?: Get,
"put"?: Put,
"post"?: Post,
"delete"?: Delete,
"options"?: Options,
"head"?: Head,
"patch"?: Patch,
"trace"?: Trace,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference
export type PathItemOrReference = (PathItemOrReferenceThen |
PathItemOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation
export type Operation = (SpecificationExtensions) &
((
{
"tags"?: OperationTags,
"summary"?: OperationSummary,
"description"?: OperationDescription,
"externalDocs"?: OperationExternalDocs,
"operationId"?: OperationOperationId,
"parameters"?: OperationParameters,
"requestBody"?: OperationRequestBody,
"responses"?: OperationResponses,
"callbacks"?: OperationCallbacks,
"deprecated"?: OperationDeprecated,
"security"?: OperationSecurity,
"servers"?: OperationServers,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/external-documentation
export type ExternalDocumentation = (SpecificationExtensions) &
((
{
"description"?: ExternalDocumentationDescription,
"url": ExternalDocumentationUrl,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter
export type Parameter = (SpecificationExtensions) &
(ParameterOneOf0 |
ParameterOneOf1) &
(ParameterThen) &
((
{
"name": ParameterName,
"in": PropertiesParameterIn,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"schema"?: ParameterSchema,
"content"?: ParameterContent,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference
export type ParameterOrReference = (ParameterOrReferenceThen |
ParameterOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body
export type RequestBody = (SpecificationExtensions) &
((
{
"description"?: RequestBodyDescription,
"content": RequestBodyContent,
"required"?: RequestBodyRequired,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference
export type RequestBodyOrReference = (RequestBodyOrReferenceThen |
RequestBodyOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/content
export type Content = ((
{
[key: ContentPropertyNames]: ContentAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type
export type MediaType = (MediaType0 &
MediaType1) &
((
{
"schema"?: MediaTypeSchema,
"encoding"?: MediaTypeEncoding,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding
export type Encoding = (EncodingAllOf0 &
EncodingAllOf1) &
((
{
"contentType"?: ContentType,
"headers"?: EncodingHeaders,
"style"?: EncodingStyle,
"explode"?: EncodingExplode,
"allowReserved"?: AllowReserved,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/responses
export type Responses = (SpecificationExtensions) &
((
{
"default"?: ResponsesDefault,
[key: string]: PatternProperties15092Xx |
ResponsesDefault |
undefined,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response
export type Response = (SpecificationExtensions) &
((
{
"description": ResponseDescription,
"headers"?: ResponseHeaders,
"content"?: ResponseContent,
"links"?: ResponseLinks,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference
export type ResponseOrReference = (ResponseOrReferenceThen |
ResponseOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks
export type Callbacks = (SpecificationExtensions) &
((
{
[key: string]: CallbacksAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference
export type CallbacksOrReference = (CallbacksOrReferenceThen |
CallbacksOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example
export type Example = (SpecificationExtensions) &
(Not) &
((
{
"summary"?: ExampleSummary,
"description"?: ExampleDescription,
"value"?: Value,
"externalValue"?: ExternalValue,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference
export type ExampleOrReference = (ExampleOrReferenceThen |
ExampleOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link
export type Link = (SpecificationExtensions) &
(LinkOneOf0 |
LinkOneOf1) &
((
{
"operationRef"?: OperationRef,
"operationId"?: LinkOperationId,
"parameters"?: LinkParameters,
"requestBody"?: LinkRequestBody,
"description"?: LinkDescription,
"body"?: Body,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference
export type LinkOrReference = (LinkOrReferenceThen |
LinkOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header
export type Header = (SpecificationExtensions) &
(HeaderOneOf0 |
HeaderOneOf1) &
((
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"schema"?: HeaderSchema,
"content"?: HeaderContent,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference
export type HeaderOrReference = (HeaderOrReferenceThen |
HeaderOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag
export type Tag = (SpecificationExtensions) &
((
{
"name": TagName,
"description"?: TagDescription,
"externalDocs"?: TagExternalDocs,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference
export type Reference = ((
{
"$ref"?: Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/schema
export type Schema = ((
{
}
) |
(boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme
export type SecurityScheme = (SecuritySchemeAllOf0 &
SecuritySchemeAllOf1 &
AllOf2 &
AllOf3 &
AllOf4 &
AllOf5) &
((
{
"type": SecuritySchemeType,
"description"?: SecuritySchemeDescription,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference
export type SecuritySchemeOrReference = (SecuritySchemeOrReferenceThen |
SecuritySchemeOrReferenceElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows
export type OauthFlows = (SpecificationExtensions) &
((
{
"implicit"?: PropertiesOauthFlowsImplicit,
"password"?: PropertiesOauthFlowsPassword,
"clientCredentials"?: PropertiesOauthFlowsClientCredentials,
"authorizationCode"?: PropertiesOauthFlowsAuthorizationCode,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-requirement
export type SecurityRequirement = ((
{
[key: string]: SecurityRequirementAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/specification-extensions
export type SpecificationExtensions = unknown;
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples
export type Examples = ((
{
"example"?: ExamplesExample,
"examples"?: ExamplesExamples,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/map-of-strings
export type MapOfStrings = ((
{
[key: string]: MapOfStringsAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/openapi
export type Openapi = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/info
export type PropertiesInfo = (Info);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/jsonSchemaDialect
export type JsonSchemaDialect = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/servers
export type PropertiesServers = (((PropertiesServersItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/paths
export type PropertiesPaths = (Paths);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/webhooks
export type Webhooks = ((
{
[key: string]: WebhooksAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/components
export type PropertiesComponents = (Components);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/security
export type PropertiesSecurity = (((PropertiesSecurityItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/tags
export type PropertiesTags = (((PropertiesTagsItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/externalDocs
export type PropertiesExternalDocs = (ExternalDocumentation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/anyOf/0
export type AnyOf0 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/anyOf/1
export type AnyOf1 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/anyOf/2
export type AnyOf2 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/title
export type Title = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/summary
export type InfoSummary = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/description
export type InfoDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/termsOfService
export type TermsOfService = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/contact
export type InfoContact = (Contact);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/license
export type InfoLicense = (License);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/version
export type Version = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact/properties/name
export type ContactName = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact/properties/url
export type ContactUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact/properties/email
export type Email = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license/properties/name
export type LicenseName = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license/properties/identifier
export type Identifier = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license/properties/url
export type LicenseUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/url
export type ServerUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/description
export type ServerDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/variables
export type Variables = ((
{
[key: string]: VariablesAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/enum
export type Enum = (((EnumItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/default
export type ServerVariableDefault = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/description
export type ServerVariableDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/schemas
export type Schemas = ((
{
[key: string]: SchemasAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/responses
export type ComponentsResponses = ((
{
[key: string]: ResponsesAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/parameters
export type ComponentsParameters = ((
{
[key: string]: ParametersAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/examples
export type ComponentsExamples = ((
{
[key: string]: ComponentsExamplesAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/requestBodies
export type RequestBodies = ((
{
[key: string]: RequestBodiesAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/headers
export type ComponentsHeaders = ((
{
[key: string]: ComponentsHeadersAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/securitySchemes
export type SecuritySchemes = ((
{
[key: string]: SecuritySchemesAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/links
export type ComponentsLinks = ((
{
[key: string]: ComponentsLinksAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/callbacks
export type ComponentsCallbacks = ((
{
[key: string]: ComponentsCallbacksAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/pathItems
export type PathItems = ((
{
[key: string]: PathItemsAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/patternProperties/^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$
export type SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItems = unknown;
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/paths/patternProperties/^/
export type PatternProperties = (PathItem);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/summary
export type PathItemSummary = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/description
export type PathItemDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/servers
export type PathItemServers = (((PathItemServersItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/parameters
export type PathItemParameters = (((PathItemParametersItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/get
export type Get = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/put
export type Put = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/post
export type Post = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/delete
export type Delete = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/options
export type Options = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/head
export type Head = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/patch
export type Patch = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/trace
export type Trace = (Operation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference/if
export type PathItemOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference/then
export type PathItemOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference/else
export type PathItemOrReferenceElse = (PathItem);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/tags
export type OperationTags = (((OperationTagsItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/summary
export type OperationSummary = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/description
export type OperationDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/externalDocs
export type OperationExternalDocs = (ExternalDocumentation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/operationId
export type OperationOperationId = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/parameters
export type OperationParameters = (((OperationParametersItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/requestBody
export type OperationRequestBody = (RequestBodyOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/responses
export type OperationResponses = (Responses);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/callbacks
export type OperationCallbacks = ((
{
[key: string]: OperationCallbacksAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/deprecated
export type OperationDeprecated = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/security
export type OperationSecurity = (((OperationSecurityItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/servers
export type OperationServers = (((OperationServersItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/external-documentation/properties/description
export type ExternalDocumentationDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/external-documentation/properties/url
export type ExternalDocumentationUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/name
export type ParameterName = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/in
export type PropertiesParameterIn = (("query" |
"header" |
"path" |
"cookie"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/description
export type ParameterDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/required
export type ParameterRequired = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/deprecated
export type ParameterDeprecated = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/schema
export type ParameterSchema = (Schema);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/content
export type ParameterContent = (Content) &
((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/oneOf/0
export type ParameterOneOf0 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/oneOf/1
export type ParameterOneOf1 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/if
export type ParameterIf = ((
{
"in": IfParameterIn,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/then
export type ParameterThen = ((
{
"allowEmptyValue"?: AllowEmptyValue,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference/if
export type ParameterOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference/then
export type ParameterOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference/else
export type ParameterOrReferenceElse = (Parameter);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body/properties/description
export type RequestBodyDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body/properties/content
export type RequestBodyContent = (Content);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body/properties/required
export type RequestBodyRequired = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference/if
export type RequestBodyOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference/then
export type RequestBodyOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference/else
export type RequestBodyOrReferenceElse = (RequestBody);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/content/additionalProperties
export type ContentAdditionalProperties = (MediaType);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/content/propertyNames
export type ContentPropertyNames = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/properties/schema
export type MediaTypeSchema = (Schema);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/properties/encoding
export type MediaTypeEncoding = ((
{
[key: string]: MediaTypeAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/allOf/0
export type MediaType0 = (SpecificationExtensions);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/allOf/1
export type MediaType1 = (Examples);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default
export type ExplodeDefault = (ExplodeDefaultThen |
ExplodeDefaultElse);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/contentType
export type ContentType = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/headers
export type EncodingHeaders = ((
{
[key: string]: EncodingHeadersAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/style
export type EncodingStyle = (("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/explode
export type EncodingExplode = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/allowReserved
export type AllowReserved = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/allOf/0
export type EncodingAllOf0 = (SpecificationExtensions);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/allOf/1
export type EncodingAllOf1 = (ExplodeDefault);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/responses/properties/default
export type ResponsesDefault = (ResponseOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/responses/patternProperties/^[1-5](?:[0-9]{2}|XX)$
export type PatternProperties15092Xx = (ResponseOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/description
export type ResponseDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/headers
export type ResponseHeaders = ((
{
[key: string]: ResponseHeadersAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/content
export type ResponseContent = (Content);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/links
export type ResponseLinks = ((
{
[key: string]: ResponseLinksAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference/if
export type ResponseOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference/then
export type ResponseOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference/else
export type ResponseOrReferenceElse = (Response);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks/additionalProperties
export type CallbacksAdditionalProperties = (PathItemOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference/if
export type CallbacksOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference/then
export type CallbacksOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference/else
export type CallbacksOrReferenceElse = (Callbacks);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/summary
export type ExampleSummary = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/description
export type ExampleDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/value
export type Value = ((any));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/externalValue
export type ExternalValue = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/not
export type Not = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference/if
export type ExampleOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference/then
export type ExampleOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference/else
export type ExampleOrReferenceElse = (Example);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/operationRef
export type OperationRef = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/operationId
export type LinkOperationId = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/parameters
export type LinkParameters = (MapOfStrings);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/requestBody
export type LinkRequestBody = ((any));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/description
export type LinkDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/body
export type Body = (Server);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/oneOf/0
export type LinkOneOf0 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/oneOf/1
export type LinkOneOf1 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference/if
export type LinkOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference/then
export type LinkOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference/else
export type LinkOrReferenceElse = (Link);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/description
export type HeaderDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/required
export type HeaderRequired = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/deprecated
export type HeaderDeprecated = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/schema
export type HeaderSchema = (Schema);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/content
export type HeaderContent = (Content) &
((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/oneOf/0
export type HeaderOneOf0 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/oneOf/1
export type HeaderOneOf1 = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference/if
export type HeaderOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference/then
export type HeaderOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference/else
export type HeaderOrReferenceElse = (Header);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag/properties/name
export type TagName = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag/properties/description
export type TagDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag/properties/externalDocs
export type TagExternalDocs = (ExternalDocumentation);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference/properties/$ref
export type Ref = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference/properties/summary
export type ReferenceSummary = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference/properties/description
export type ReferenceDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey
export type TypeApikey = (TypeApikeyThen);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http
export type TypeHttp = (TypeHttpThen);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer
export type TypeHttpBearer = (TypeHttpBearerThen);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2
export type TypeOauth2 = (TypeOauth2Then);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc
export type TypeOidc = (TypeOidcThen);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/properties/type
export type SecuritySchemeType = (("apiKey" |
"http" |
"mutualTLS" |
"oauth2" |
"openIdConnect"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/properties/description
export type SecuritySchemeDescription = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/0
export type SecuritySchemeAllOf0 = (SpecificationExtensions);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/1
export type SecuritySchemeAllOf1 = (TypeApikey);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/2
export type AllOf2 = (TypeHttp);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/3
export type AllOf3 = (TypeHttpBearer);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/4
export type AllOf4 = (TypeOauth2);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/5
export type AllOf5 = (TypeOidc);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference/if
export type SecuritySchemeOrReferenceIf = ((
{
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference/then
export type SecuritySchemeOrReferenceThen = (Reference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference/else
export type SecuritySchemeOrReferenceElse = (SecurityScheme);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit
export type DefsOauthFlowsImplicit = (SpecificationExtensions) &
((
{
"authorizationUrl": ImplicitAuthorizationUrl,
"refreshUrl"?: ImplicitRefreshUrl,
"scopes": ImplicitScopes,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password
export type DefsOauthFlowsPassword = (SpecificationExtensions) &
((
{
"tokenUrl": PasswordTokenUrl,
"refreshUrl"?: PasswordRefreshUrl,
"scopes": PasswordScopes,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials
export type DefsOauthFlowsClientCredentials = (SpecificationExtensions) &
((
{
"tokenUrl": ClientCredentialsTokenUrl,
"refreshUrl"?: ClientCredentialsRefreshUrl,
"scopes": ClientCredentialsScopes,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code
export type DefsOauthFlowsAuthorizationCode = (SpecificationExtensions) &
((
{
"authorizationUrl": AuthorizationCodeAuthorizationUrl,
"tokenUrl": AuthorizationCodeTokenUrl,
"refreshUrl"?: AuthorizationCodeRefreshUrl,
"scopes": AuthorizationCodeScopes,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/implicit
export type PropertiesOauthFlowsImplicit = (DefsOauthFlowsImplicit);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/password
export type PropertiesOauthFlowsPassword = (DefsOauthFlowsPassword);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/clientCredentials
export type PropertiesOauthFlowsClientCredentials = (DefsOauthFlowsClientCredentials);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/authorizationCode
export type PropertiesOauthFlowsAuthorizationCode = (DefsOauthFlowsAuthorizationCode);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-requirement/additionalProperties
export type SecurityRequirementAdditionalProperties = (((SecurityRequirementItems)[]));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/specification-extensions/patternProperties/^x-
export type X = ((any));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples/properties/example
export type ExamplesExample = ((any));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples/properties/examples
export type ExamplesExamples = ((
{
[key: string]: ExamplesExamplesAdditionalProperties,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/map-of-strings/additionalProperties
export type MapOfStringsAdditionalProperties = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/servers/items
export type PropertiesServersItems = (Server);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/webhooks/additionalProperties
export type WebhooksAdditionalProperties = (PathItemOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/security/items
export type PropertiesSecurityItems = (SecurityRequirement);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/tags/items
export type PropertiesTagsItems = (Tag);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/variables/additionalProperties
export type VariablesAdditionalProperties = (ServerVariable);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/enum/items
export type EnumItems = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/schemas/additionalProperties
export type SchemasAdditionalProperties = (Schema);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/responses/additionalProperties
export type ResponsesAdditionalProperties = (ResponseOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/parameters/additionalProperties
export type ParametersAdditionalProperties = (ParameterOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/examples/additionalProperties
export type ComponentsExamplesAdditionalProperties = (ExampleOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/requestBodies/additionalProperties
export type RequestBodiesAdditionalProperties = (RequestBodyOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/headers/additionalProperties
export type ComponentsHeadersAdditionalProperties = (HeaderOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/securitySchemes/additionalProperties
export type SecuritySchemesAdditionalProperties = (SecuritySchemeOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/links/additionalProperties
export type ComponentsLinksAdditionalProperties = (LinkOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/callbacks/additionalProperties
export type ComponentsCallbacksAdditionalProperties = (CallbacksOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/pathItems/additionalProperties
export type PathItemsAdditionalProperties = (PathItemOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/patternProperties/^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$/propertyNames
export type SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsPropertyNames = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/servers/items
export type PathItemServersItems = (Server);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/parameters/items
export type PathItemParametersItems = (ParameterOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/tags/items
export type OperationTagsItems = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/parameters/items
export type OperationParametersItems = (ParameterOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/callbacks/additionalProperties
export type OperationCallbacksAdditionalProperties = (CallbacksOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/security/items
export type OperationSecurityItems = (SecurityRequirement);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/servers/items
export type OperationServersItems = (Server);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/if/properties/in
export type IfParameterIn = (("query"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/then/properties/allowEmptyValue
export type AllowEmptyValue = ((boolean));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/properties/encoding/additionalProperties
export type MediaTypeAdditionalProperties = (Encoding);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/if
export type ExplodeDefaultIf = ((
{
"style": ExplodeDefaultStyle,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/then
export type ExplodeDefaultThen = ((
{
"explode"?: EncodingExplodeDefaultExplode,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/else
export type ExplodeDefaultElse = ((
{
"explode"?: ElseExplodeDefaultExplode,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/headers/additionalProperties
export type EncodingHeadersAdditionalProperties = (HeaderOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/headers/additionalProperties
export type ResponseHeadersAdditionalProperties = (HeaderOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/links/additionalProperties
export type ResponseLinksAdditionalProperties = (LinkOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/if
export type TypeApikeyIf = ((
{
"type": TypeApikeyType,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/then
export type TypeApikeyThen = ((
{
"name": TypeApikeyName,
"in": TypeApikeyIn,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/if
export type TypeHttpIf = ((
{
"type": TypeHttpType,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/then
export type TypeHttpThen = ((
{
"scheme": TypeHttpScheme,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/if
export type TypeHttpBearerIf = ((
{
"type": TypeHttpBearerType,
"scheme": TypeHttpBearerScheme,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/then
export type TypeHttpBearerThen = ((
{
"bearerFormat"?: BearerFormat,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/if
export type TypeOauth2If = ((
{
"type": TypeOauth2Type,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/then
export type TypeOauth2Then = ((
{
"flows": Flows,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/if
export type TypeOidcIf = ((
{
"type": TypeOidcType,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/then
export type TypeOidcThen = ((
{
"openIdConnectUrl": OpenIdConnectUrl,
}
));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit/properties/authorizationUrl
export type ImplicitAuthorizationUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit/properties/refreshUrl
export type ImplicitRefreshUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit/properties/scopes
export type ImplicitScopes = (MapOfStrings);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password/properties/tokenUrl
export type PasswordTokenUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password/properties/refreshUrl
export type PasswordRefreshUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password/properties/scopes
export type PasswordScopes = (MapOfStrings);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials/properties/tokenUrl
export type ClientCredentialsTokenUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials/properties/refreshUrl
export type ClientCredentialsRefreshUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials/properties/scopes
export type ClientCredentialsScopes = (MapOfStrings);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/authorizationUrl
export type AuthorizationCodeAuthorizationUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/tokenUrl
export type AuthorizationCodeTokenUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/refreshUrl
export type AuthorizationCodeRefreshUrl = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/scopes
export type AuthorizationCodeScopes = (MapOfStrings);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-requirement/additionalProperties/items
export type SecurityRequirementItems = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples/properties/examples/additionalProperties
export type ExamplesExamplesAdditionalProperties = (ExampleOrReference);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/if/properties/style
export type ExplodeDefaultStyle = (("form"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/then/properties/explode
export type EncodingExplodeDefaultExplode = unknown;
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/else/properties/explode
export type ElseExplodeDefaultExplode = unknown;
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/if/properties/type
export type TypeApikeyType = (("apiKey"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/then/properties/name
export type TypeApikeyName = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/then/properties/in
export type TypeApikeyIn = (("query" |
"header" |
"cookie"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/if/properties/type
export type TypeHttpType = (("http"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/then/properties/scheme
export type TypeHttpScheme = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/if/properties/type
export type TypeHttpBearerType = (("http"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/if/properties/scheme
export type TypeHttpBearerScheme = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/then/properties/bearerFormat
export type BearerFormat = ((string));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/if/properties/type
export type TypeOauth2Type = (("oauth2"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/then/properties/flows
export type Flows = (OauthFlows);
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/if/properties/type
export type TypeOidcType = (("openIdConnect"));
// https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/then/properties/openIdConnectUrl
export type OpenIdConnectUrl = ((string));
