// @generated by
//     __             _____     _                 ___ ___
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
// v0.12.10                        -- www.JsonSchema42.org
//
/**
* @description The description of OpenAPI v3.1.x documents without schema validation, as defined by https://spec.openapis.org/oas/v3.1.0
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07}
*/
export type SchemaDocument = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info}
*/
export type Info = (
{
"title": Title,
"summary"?: InfoSummary,
"description"?: InfoDescription,
"termsOfService"?: TermsOfService,
"contact"?: InfoContact,
"license"?: InfoLicense,
"version": Version,
[
name: string
]: X |
Title |
InfoSummary |
InfoDescription |
TermsOfService |
InfoContact |
InfoLicense |
Version |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact}
*/
export type Contact = (
{
"name"?: ContactName,
"url"?: ContactUrl,
"email"?: Email,
[
name: string
]: X |
ContactName |
ContactUrl |
Email |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license}
*/
export type License = (
{
"name": LicenseName,
"identifier"?: Identifier,
"url"?: LicenseUrl,
[
name: string
]: X |
LicenseName |
Identifier |
LicenseUrl |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server}
*/
export type Server = (
{
"url": ServerUrl,
"description"?: ServerDescription,
"variables"?: Variables,
[
name: string
]: X |
ServerUrl |
ServerDescription |
Variables |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable}
*/
export type ServerVariable = (
{
"enum"?: Enum,
"default": ServerVariableDefault,
"description"?: ServerVariableDescription,
[
name: string
]: X |
Enum |
ServerVariableDefault |
ServerVariableDescription |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components}
*/
export type Components = (
{
"schemas"?: Schemas,
"responses"?: ComponentsResponses,
"parameters"?: ComponentsParameters,
"examples"?: ComponentsExamples,
"requestBodies"?: RequestBodies,
"headers"?: ComponentsHeaders,
"securitySchemes"?: SecuritySchemes,
"links"?: ComponentsLinks,
"callbacks"?: ComponentsCallbacks,
"pathItems"?: PathItems,
[
name: string
]: X |
Schemas |
ComponentsResponses |
ComponentsParameters |
ComponentsExamples |
RequestBodies |
ComponentsHeaders |
SecuritySchemes |
ComponentsLinks |
ComponentsCallbacks |
PathItems |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/paths}
*/
export type Paths = (
{
[
name: string
]: X
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item}
*/
export type PathItem = (
{
"summary"?: PathItemSummary,
"description"?: PathItemDescription,
"servers"?: PathItemServers,
"parameters"?: PathItemParameters,
"get"?: Get,
"put"?: Put,
"post"?: Post,
"delete"?: Delete,
"options"?: Options,
"head"?: Head,
"patch"?: Patch,
"trace"?: Trace,
[
name: string
]: X |
PathItemSummary |
PathItemDescription |
PathItemServers |
PathItemParameters |
Get |
Put |
Post |
Delete |
Options |
Head |
Patch |
Trace |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference}
*/
export type PathItemOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"summary"?: PathItemSummary,
"description"?: PathItemDescription,
"servers"?: PathItemServers,
"parameters"?: PathItemParameters,
"get"?: Get,
"put"?: Put,
"post"?: Post,
"delete"?: Delete,
"options"?: Options,
"head"?: Head,
"patch"?: Patch,
"trace"?: Trace,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation}
*/
export type Operation = (
{
"tags"?: OperationTags,
"summary"?: OperationSummary,
"description"?: OperationDescription,
"externalDocs"?: OperationExternalDocs,
"operationId"?: OperationOperationId,
"parameters"?: OperationParameters,
"requestBody"?: OperationRequestBody,
"responses"?: OperationResponses,
"callbacks"?: OperationCallbacks,
"deprecated"?: OperationDeprecated,
"security"?: OperationSecurity,
"servers"?: OperationServers,
[
name: string
]: X |
OperationTags |
OperationSummary |
OperationDescription |
OperationExternalDocs |
OperationOperationId |
OperationParameters |
OperationRequestBody |
OperationResponses |
OperationCallbacks |
OperationDeprecated |
OperationSecurity |
OperationServers |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/external-documentation}
*/
export type ExternalDocumentation = (
{
"description"?: ExternalDocumentationDescription,
"url": ExternalDocumentationUrl,
[
name: string
]: X |
ExternalDocumentationDescription |
ExternalDocumentationUrl |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter}
*/
export type Parameter = (
(
{
"in": ("query"),
"allowEmptyValue"?: AllowEmptyValue,
"name": ParameterName,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"schema": ParameterSchema,
"content"?: ParameterContent,
[
name: string
]: X |
("query") |
AllowEmptyValue |
ParameterName |
ParameterDescription |
ParameterRequired |
ParameterDeprecated |
ParameterSchema |
ParameterContent |
undefined
}
)
|
(
{
"in": ("query"),
"allowEmptyValue"?: AllowEmptyValue,
"name": ParameterName,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"schema"?: ParameterSchema,
"content": ParameterContent,
[
name: string
]: X |
("query") |
AllowEmptyValue |
ParameterName |
ParameterDescription |
ParameterRequired |
ParameterDeprecated |
ParameterSchema |
ParameterContent |
undefined
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference}
*/
export type ParameterOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"in": ("query"),
"allowEmptyValue"?: AllowEmptyValue,
"name": ParameterName,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"schema": ParameterSchema,
"content"?: ParameterContent,
[
name: string
]: any
}
)
|
(
{
"in": ("query"),
"allowEmptyValue"?: AllowEmptyValue,
"name": ParameterName,
"description"?: ParameterDescription,
"required"?: ParameterRequired,
"deprecated"?: ParameterDeprecated,
"schema"?: ParameterSchema,
"content": ParameterContent,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body}
*/
export type RequestBody = (
{
"description"?: RequestBodyDescription,
"content": RequestBodyContent,
"required"?: RequestBodyRequired,
[
name: string
]: X |
RequestBodyDescription |
RequestBodyContent |
RequestBodyRequired |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference}
*/
export type RequestBodyOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"description"?: RequestBodyDescription,
"content": RequestBodyContent,
"required"?: RequestBodyRequired,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/content}
*/
export type Content = (
{
[
name: ContentPropertyNames
]: ContentAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type}
*/
export type MediaType = (
{
"example"?: ExamplesExample,
"examples"?: ExamplesExamples,
"schema"?: MediaTypeSchema,
"encoding"?: MediaTypeEncoding,
[
name: string
]: X |
ExamplesExample |
ExamplesExamples |
MediaTypeSchema |
MediaTypeEncoding |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding}
*/
export type Encoding = (
(
{
"contentType"?: ContentType,
"headers"?: EncodingHeaders,
"style": ("form"),
"explode"?: (boolean),
"allowReserved"?: AllowReserved,
[
name: string
]: X |
ContentType |
EncodingHeaders |
("form") |
(boolean) |
AllowReserved |
undefined
}
)
|
(
{
"contentType"?: ContentType,
"headers"?: EncodingHeaders,
"style"?: EncodingStyle,
"explode"?: (boolean),
"allowReserved"?: AllowReserved,
[
name: string
]: X |
ContentType |
EncodingHeaders |
EncodingStyle |
(boolean) |
AllowReserved |
undefined
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/responses}
*/
export type Responses = (
{
"default"?: ResponsesDefault,
[
name: string
]: X |
ResponsesDefault |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response}
*/
export type Response = (
{
"description": ResponseDescription,
"headers"?: ResponseHeaders,
"content"?: ResponseContent,
"links"?: ResponseLinks,
[
name: string
]: X |
ResponseDescription |
ResponseHeaders |
ResponseContent |
ResponseLinks |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference}
*/
export type ResponseOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"description": ResponseDescription,
"headers"?: ResponseHeaders,
"content"?: ResponseContent,
"links"?: ResponseLinks,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks}
*/
export type Callbacks = (
{
[
name: string
]: CallbacksAdditionalProperties |
X
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference}
*/
export type CallbacksOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
[
name: string
]: CallbacksAdditionalProperties
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example}
*/
export type Example = (
{
"summary"?: ExampleSummary,
"description"?: ExampleDescription,
"value"?: Value,
"externalValue"?: ExternalValue,
[
name: string
]: X |
ExampleSummary |
ExampleDescription |
Value |
ExternalValue |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference}
*/
export type ExampleOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"summary"?: ExampleSummary,
"description"?: ExampleDescription,
"value"?: Value,
"externalValue"?: ExternalValue,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link}
*/
export type Link = (
(
{
"operationRef": OperationRef,
"operationId"?: LinkOperationId,
"parameters"?: LinkParameters,
"requestBody"?: LinkRequestBody,
"description"?: LinkDescription,
"body"?: Body,
[
name: string
]: X |
OperationRef |
LinkOperationId |
LinkParameters |
LinkRequestBody |
LinkDescription |
Body |
undefined
}
)
|
(
{
"operationRef"?: OperationRef,
"operationId": LinkOperationId,
"parameters"?: LinkParameters,
"requestBody"?: LinkRequestBody,
"description"?: LinkDescription,
"body"?: Body,
[
name: string
]: X |
OperationRef |
LinkOperationId |
LinkParameters |
LinkRequestBody |
LinkDescription |
Body |
undefined
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference}
*/
export type LinkOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"operationRef": OperationRef,
"operationId"?: LinkOperationId,
"parameters"?: LinkParameters,
"requestBody"?: LinkRequestBody,
"description"?: LinkDescription,
"body"?: Body,
[
name: string
]: any
}
)
|
(
{
"operationRef"?: OperationRef,
"operationId": LinkOperationId,
"parameters"?: LinkParameters,
"requestBody"?: LinkRequestBody,
"description"?: LinkDescription,
"body"?: Body,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header}
*/
export type Header = (
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"schema": HeaderSchema,
"content"?: HeaderContent,
[
name: string
]: X |
HeaderDescription |
HeaderRequired |
HeaderDeprecated |
HeaderSchema |
HeaderContent |
undefined
}
)
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"schema"?: HeaderSchema,
"content": HeaderContent,
[
name: string
]: X |
HeaderDescription |
HeaderRequired |
HeaderDeprecated |
HeaderSchema |
HeaderContent |
undefined
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference}
*/
export type HeaderOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"schema": HeaderSchema,
"content"?: HeaderContent,
[
name: string
]: any
}
)
|
(
{
"description"?: HeaderDescription,
"required"?: HeaderRequired,
"deprecated"?: HeaderDeprecated,
"schema"?: HeaderSchema,
"content": HeaderContent,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag}
*/
export type Tag = (
{
"name": TagName,
"description"?: TagDescription,
"externalDocs"?: TagExternalDocs,
[
name: string
]: X |
TagName |
TagDescription |
TagExternalDocs |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference}
*/
export type Reference = (
{
"$ref"?: Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/schema}
*/
export type Schema = (
(
{
[
name: string
]: any
}
)
|
(boolean)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme}
*/
export type SecurityScheme = (
{
"type": (unknown),
"name": TypeApikeyName,
"in": TypeApikeyIn,
"scheme": (string),
"bearerFormat"?: BearerFormat,
"flows": Flows,
"openIdConnectUrl": OpenIdConnectUrl,
"description"?: SecuritySchemeDescription,
[
name: string
]: X |
(unknown) |
TypeApikeyName |
TypeApikeyIn |
(string) |
BearerFormat |
Flows |
OpenIdConnectUrl |
SecuritySchemeDescription |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference}
*/
export type SecuritySchemeOrReference = (
(
{
"$ref": Ref,
"summary"?: ReferenceSummary,
"description"?: ReferenceDescription,
[
name: string
]: any
}
)
|
(
{
"type": (unknown),
"name": TypeApikeyName,
"in": TypeApikeyIn,
"scheme": (string),
"bearerFormat"?: BearerFormat,
"flows": Flows,
"openIdConnectUrl": OpenIdConnectUrl,
"description"?: SecuritySchemeDescription,
[
name: string
]: any
}
)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows}
*/
export type OauthFlows = (
{
"implicit"?: PropertiesOauthFlowsImplicit,
"password"?: PropertiesOauthFlowsPassword,
"clientCredentials"?: PropertiesOauthFlowsClientCredentials,
"authorizationCode"?: PropertiesOauthFlowsAuthorizationCode,
[
name: string
]: X |
PropertiesOauthFlowsImplicit |
PropertiesOauthFlowsPassword |
PropertiesOauthFlowsClientCredentials |
PropertiesOauthFlowsAuthorizationCode |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-requirement}
*/
export type SecurityRequirement = (
{
[
name: string
]: SecurityRequirementAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/specification-extensions}
*/
export type SpecificationExtensions = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples}
*/
export type Examples = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/map-of-strings}
*/
export type MapOfStrings = (
{
[
name: string
]: MapOfStringsAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/openapi}
*/
export type Openapi = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/info}
*/
export type PropertiesInfo = (Info);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/jsonSchemaDialect}
*/
export type JsonSchemaDialect = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/servers}
*/
export type PropertiesServers = (
[
...(PropertiesServersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/paths}
*/
export type PropertiesPaths = (Paths);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/webhooks}
*/
export type Webhooks = (
{
[
name: string
]: WebhooksAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/components}
*/
export type PropertiesComponents = (Components);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/security}
*/
export type PropertiesSecurity = (
[
...(PropertiesSecurityItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/tags}
*/
export type PropertiesTags = (
[
...(PropertiesTagsItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/externalDocs}
*/
export type PropertiesExternalDocs = (ExternalDocumentation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/anyOf/0}
*/
export type AnyOf0 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/anyOf/1}
*/
export type AnyOf1 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/anyOf/2}
*/
export type AnyOf2 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/title}
*/
export type Title = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/summary}
*/
export type InfoSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/description}
*/
export type InfoDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/termsOfService}
*/
export type TermsOfService = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/contact}
*/
export type InfoContact = (Contact);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/license}
*/
export type InfoLicense = (License);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/info/properties/version}
*/
export type Version = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact/properties/name}
*/
export type ContactName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact/properties/url}
*/
export type ContactUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/contact/properties/email}
*/
export type Email = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license/properties/name}
*/
export type LicenseName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license/properties/identifier}
*/
export type Identifier = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/license/properties/url}
*/
export type LicenseUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/url}
*/
export type ServerUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/description}
*/
export type ServerDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/variables}
*/
export type Variables = (
{
[
name: string
]: VariablesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/enum}
*/
export type Enum = (
[
...(EnumItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/default}
*/
export type ServerVariableDefault = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/description}
*/
export type ServerVariableDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/schemas}
*/
export type Schemas = (
{
[
name: string
]: SchemasAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/responses}
*/
export type ComponentsResponses = (
{
[
name: string
]: ResponsesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/parameters}
*/
export type ComponentsParameters = (
{
[
name: string
]: ParametersAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/examples}
*/
export type ComponentsExamples = (
{
[
name: string
]: ComponentsExamplesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/requestBodies}
*/
export type RequestBodies = (
{
[
name: string
]: RequestBodiesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/headers}
*/
export type ComponentsHeaders = (
{
[
name: string
]: ComponentsHeadersAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/securitySchemes}
*/
export type SecuritySchemes = (
{
[
name: string
]: SecuritySchemesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/links}
*/
export type ComponentsLinks = (
{
[
name: string
]: ComponentsLinksAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/callbacks}
*/
export type ComponentsCallbacks = (
{
[
name: string
]: ComponentsCallbacksAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/pathItems}
*/
export type PathItems = (
{
[
name: string
]: PathItemsAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/patternProperties/^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$}
*/
export type SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItems = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/paths/patternProperties/^/}
*/
export type PatternProperties = (PathItem);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/summary}
*/
export type PathItemSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/description}
*/
export type PathItemDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/servers}
*/
export type PathItemServers = (
[
...(PathItemServersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/parameters}
*/
export type PathItemParameters = (
[
...(PathItemParametersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/get}
*/
export type Get = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/put}
*/
export type Put = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/post}
*/
export type Post = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/delete}
*/
export type Delete = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/options}
*/
export type Options = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/head}
*/
export type Head = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/patch}
*/
export type Patch = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/trace}
*/
export type Trace = (Operation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference/if}
*/
export type PathItemOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference/then}
*/
export type PathItemOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item-or-reference/else}
*/
export type PathItemOrReferenceElse = (PathItem);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/tags}
*/
export type OperationTags = (
[
...(OperationTagsItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/summary}
*/
export type OperationSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/description}
*/
export type OperationDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/externalDocs}
*/
export type OperationExternalDocs = (ExternalDocumentation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/operationId}
*/
export type OperationOperationId = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/parameters}
*/
export type OperationParameters = (
[
...(OperationParametersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/requestBody}
*/
export type OperationRequestBody = (RequestBodyOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/responses}
*/
export type OperationResponses = (Responses);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/callbacks}
*/
export type OperationCallbacks = (
{
[
name: string
]: OperationCallbacksAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/deprecated}
*/
export type OperationDeprecated = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/security}
*/
export type OperationSecurity = (
[
...(OperationSecurityItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/servers}
*/
export type OperationServers = (
[
...(OperationServersItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/external-documentation/properties/description}
*/
export type ExternalDocumentationDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/external-documentation/properties/url}
*/
export type ExternalDocumentationUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/name}
*/
export type ParameterName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/in}
*/
export type PropertiesParameterIn = ("query" |
"header" |
"path" |
"cookie");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/description}
*/
export type ParameterDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/required}
*/
export type ParameterRequired = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/deprecated}
*/
export type ParameterDeprecated = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/schema}
*/
export type ParameterSchema = (Schema);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/properties/content}
*/
export type ParameterContent = (
{
[
name: ContentPropertyNames
]: ContentAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/oneOf/0}
*/
export type ParameterOneOf0 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/oneOf/1}
*/
export type ParameterOneOf1 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/if}
*/
export type ParameterIf = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/then}
*/
export type ParameterThen = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference/if}
*/
export type ParameterOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference/then}
*/
export type ParameterOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter-or-reference/else}
*/
export type ParameterOrReferenceElse = (Parameter);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body/properties/description}
*/
export type RequestBodyDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body/properties/content}
*/
export type RequestBodyContent = (Content);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body/properties/required}
*/
export type RequestBodyRequired = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference/if}
*/
export type RequestBodyOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference/then}
*/
export type RequestBodyOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/request-body-or-reference/else}
*/
export type RequestBodyOrReferenceElse = (RequestBody);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/content/additionalProperties}
*/
export type ContentAdditionalProperties = (MediaType);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/content/propertyNames}
*/
export type ContentPropertyNames = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/properties/schema}
*/
export type MediaTypeSchema = (Schema);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/properties/encoding}
*/
export type MediaTypeEncoding = (
{
[
name: string
]: MediaTypeAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/allOf/0}
*/
export type MediaType0 = (SpecificationExtensions);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/allOf/1}
*/
export type MediaType1 = (Examples);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default}
*/
export type ExplodeDefault = (
(unknown)
|
(unknown)
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/contentType}
*/
export type ContentType = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/headers}
*/
export type EncodingHeaders = (
{
[
name: string
]: EncodingHeadersAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/style}
*/
export type EncodingStyle = ("form" |
"spaceDelimited" |
"pipeDelimited" |
"deepObject");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/explode}
*/
export type EncodingExplode = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/allowReserved}
*/
export type AllowReserved = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/allOf/0}
*/
export type EncodingAllOf0 = (SpecificationExtensions);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/allOf/1}
*/
export type EncodingAllOf1 = (ExplodeDefault);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/responses/properties/default}
*/
export type ResponsesDefault = (ResponseOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/responses/patternProperties/^[1-5](?:[0-9]{2}|XX)$}
*/
export type PatternProperties15092Xx = (ResponseOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/description}
*/
export type ResponseDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/headers}
*/
export type ResponseHeaders = (
{
[
name: string
]: ResponseHeadersAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/content}
*/
export type ResponseContent = (Content);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/links}
*/
export type ResponseLinks = (
{
[
name: string
]: ResponseLinksAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference/if}
*/
export type ResponseOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference/then}
*/
export type ResponseOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response-or-reference/else}
*/
export type ResponseOrReferenceElse = (Response);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks/additionalProperties}
*/
export type CallbacksAdditionalProperties = (PathItemOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference/if}
*/
export type CallbacksOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference/then}
*/
export type CallbacksOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/callbacks-or-reference/else}
*/
export type CallbacksOrReferenceElse = (Callbacks);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/summary}
*/
export type ExampleSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/description}
*/
export type ExampleDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/value}
*/
export type Value = (any);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/properties/externalValue}
*/
export type ExternalValue = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example/not}
*/
export type Not = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference/if}
*/
export type ExampleOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference/then}
*/
export type ExampleOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/example-or-reference/else}
*/
export type ExampleOrReferenceElse = (Example);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/operationRef}
*/
export type OperationRef = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/operationId}
*/
export type LinkOperationId = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/parameters}
*/
export type LinkParameters = (MapOfStrings);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/requestBody}
*/
export type LinkRequestBody = (any);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/description}
*/
export type LinkDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/properties/body}
*/
export type Body = (Server);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/oneOf/0}
*/
export type LinkOneOf0 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link/oneOf/1}
*/
export type LinkOneOf1 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference/if}
*/
export type LinkOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference/then}
*/
export type LinkOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/link-or-reference/else}
*/
export type LinkOrReferenceElse = (Link);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/description}
*/
export type HeaderDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/required}
*/
export type HeaderRequired = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/deprecated}
*/
export type HeaderDeprecated = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/schema}
*/
export type HeaderSchema = (Schema);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/properties/content}
*/
export type HeaderContent = (
{
[
name: ContentPropertyNames
]: ContentAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/oneOf/0}
*/
export type HeaderOneOf0 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header/oneOf/1}
*/
export type HeaderOneOf1 = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference/if}
*/
export type HeaderOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference/then}
*/
export type HeaderOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/header-or-reference/else}
*/
export type HeaderOrReferenceElse = (Header);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag/properties/name}
*/
export type TagName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag/properties/description}
*/
export type TagDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/tag/properties/externalDocs}
*/
export type TagExternalDocs = (ExternalDocumentation);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference/properties/$ref}
*/
export type Ref = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference/properties/summary}
*/
export type ReferenceSummary = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/reference/properties/description}
*/
export type ReferenceDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey}
*/
export type TypeApikey = ((unknown));
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http}
*/
export type TypeHttp = ((unknown));
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer}
*/
export type TypeHttpBearer = ((unknown));
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2}
*/
export type TypeOauth2 = ((unknown));
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc}
*/
export type TypeOidc = ((unknown));
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/properties/type}
*/
export type SecuritySchemeType = ("apiKey" |
"http" |
"mutualTLS" |
"oauth2" |
"openIdConnect");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/properties/description}
*/
export type SecuritySchemeDescription = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/0}
*/
export type SecuritySchemeAllOf0 = (SpecificationExtensions);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/1}
*/
export type SecuritySchemeAllOf1 = (TypeApikey);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/2}
*/
export type AllOf2 = (TypeHttp);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/3}
*/
export type AllOf3 = (TypeHttpBearer);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/4}
*/
export type AllOf4 = (TypeOauth2);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/allOf/5}
*/
export type AllOf5 = (TypeOidc);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference/if}
*/
export type SecuritySchemeOrReferenceIf = (
{
"$ref": any,
[
name: string
]: any
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference/then}
*/
export type SecuritySchemeOrReferenceThen = (Reference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme-or-reference/else}
*/
export type SecuritySchemeOrReferenceElse = (SecurityScheme);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit}
*/
export type DefsOauthFlowsImplicit = (
{
"authorizationUrl": ImplicitAuthorizationUrl,
"refreshUrl"?: ImplicitRefreshUrl,
"scopes": ImplicitScopes,
[
name: string
]: X |
ImplicitAuthorizationUrl |
ImplicitRefreshUrl |
ImplicitScopes |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password}
*/
export type DefsOauthFlowsPassword = (
{
"tokenUrl": PasswordTokenUrl,
"refreshUrl"?: PasswordRefreshUrl,
"scopes": PasswordScopes,
[
name: string
]: X |
PasswordTokenUrl |
PasswordRefreshUrl |
PasswordScopes |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials}
*/
export type DefsOauthFlowsClientCredentials = (
{
"tokenUrl": ClientCredentialsTokenUrl,
"refreshUrl"?: ClientCredentialsRefreshUrl,
"scopes": ClientCredentialsScopes,
[
name: string
]: X |
ClientCredentialsTokenUrl |
ClientCredentialsRefreshUrl |
ClientCredentialsScopes |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code}
*/
export type DefsOauthFlowsAuthorizationCode = (
{
"authorizationUrl": AuthorizationCodeAuthorizationUrl,
"tokenUrl": AuthorizationCodeTokenUrl,
"refreshUrl"?: AuthorizationCodeRefreshUrl,
"scopes": AuthorizationCodeScopes,
[
name: string
]: X |
AuthorizationCodeAuthorizationUrl |
AuthorizationCodeTokenUrl |
AuthorizationCodeRefreshUrl |
AuthorizationCodeScopes |
undefined
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/implicit}
*/
export type PropertiesOauthFlowsImplicit = (DefsOauthFlowsImplicit);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/password}
*/
export type PropertiesOauthFlowsPassword = (DefsOauthFlowsPassword);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/clientCredentials}
*/
export type PropertiesOauthFlowsClientCredentials = (DefsOauthFlowsClientCredentials);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/properties/authorizationCode}
*/
export type PropertiesOauthFlowsAuthorizationCode = (DefsOauthFlowsAuthorizationCode);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-requirement/additionalProperties}
*/
export type SecurityRequirementAdditionalProperties = (
[
...(SecurityRequirementItems)[]
]
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/specification-extensions/patternProperties/^x-}
*/
export type X = (any);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples/properties/example}
*/
export type ExamplesExample = (any);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples/properties/examples}
*/
export type ExamplesExamples = (
{
[
name: string
]: ExamplesExamplesAdditionalProperties
}
);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/map-of-strings/additionalProperties}
*/
export type MapOfStringsAdditionalProperties = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/servers/items}
*/
export type PropertiesServersItems = (Server);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/webhooks/additionalProperties}
*/
export type WebhooksAdditionalProperties = (PathItemOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/security/items}
*/
export type PropertiesSecurityItems = (SecurityRequirement);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/properties/tags/items}
*/
export type PropertiesTagsItems = (Tag);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server/properties/variables/additionalProperties}
*/
export type VariablesAdditionalProperties = (ServerVariable);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/server-variable/properties/enum/items}
*/
export type EnumItems = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/schemas/additionalProperties}
*/
export type SchemasAdditionalProperties = (Schema);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/responses/additionalProperties}
*/
export type ResponsesAdditionalProperties = (ResponseOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/parameters/additionalProperties}
*/
export type ParametersAdditionalProperties = (ParameterOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/examples/additionalProperties}
*/
export type ComponentsExamplesAdditionalProperties = (ExampleOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/requestBodies/additionalProperties}
*/
export type RequestBodiesAdditionalProperties = (RequestBodyOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/headers/additionalProperties}
*/
export type ComponentsHeadersAdditionalProperties = (HeaderOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/securitySchemes/additionalProperties}
*/
export type SecuritySchemesAdditionalProperties = (SecuritySchemeOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/links/additionalProperties}
*/
export type ComponentsLinksAdditionalProperties = (LinkOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/callbacks/additionalProperties}
*/
export type ComponentsCallbacksAdditionalProperties = (CallbacksOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/properties/pathItems/additionalProperties}
*/
export type PathItemsAdditionalProperties = (PathItemOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/components/patternProperties/^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$/propertyNames}
*/
export type SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsPropertyNames = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/servers/items}
*/
export type PathItemServersItems = (Server);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/path-item/properties/parameters/items}
*/
export type PathItemParametersItems = (ParameterOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/tags/items}
*/
export type OperationTagsItems = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/parameters/items}
*/
export type OperationParametersItems = (ParameterOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/callbacks/additionalProperties}
*/
export type OperationCallbacksAdditionalProperties = (CallbacksOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/security/items}
*/
export type OperationSecurityItems = (SecurityRequirement);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/operation/properties/servers/items}
*/
export type OperationServersItems = (Server);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/if/properties/in}
*/
export type IfParameterIn = ("query");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/parameter/then/properties/allowEmptyValue}
*/
export type AllowEmptyValue = (boolean);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/media-type/properties/encoding/additionalProperties}
*/
export type MediaTypeAdditionalProperties = (Encoding);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/if}
*/
export type ExplodeDefaultIf = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/then}
*/
export type ExplodeDefaultThen = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/else}
*/
export type ExplodeDefaultElse = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/properties/headers/additionalProperties}
*/
export type EncodingHeadersAdditionalProperties = (HeaderOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/headers/additionalProperties}
*/
export type ResponseHeadersAdditionalProperties = (HeaderOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/response/properties/links/additionalProperties}
*/
export type ResponseLinksAdditionalProperties = (LinkOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/if}
*/
export type TypeApikeyIf = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/then}
*/
export type TypeApikeyThen = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/if}
*/
export type TypeHttpIf = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/then}
*/
export type TypeHttpThen = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/if}
*/
export type TypeHttpBearerIf = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/then}
*/
export type TypeHttpBearerThen = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/if}
*/
export type TypeOauth2If = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/then}
*/
export type TypeOauth2Then = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/if}
*/
export type TypeOidcIf = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/then}
*/
export type TypeOidcThen = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit/properties/authorizationUrl}
*/
export type ImplicitAuthorizationUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit/properties/refreshUrl}
*/
export type ImplicitRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/implicit/properties/scopes}
*/
export type ImplicitScopes = (MapOfStrings);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password/properties/tokenUrl}
*/
export type PasswordTokenUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password/properties/refreshUrl}
*/
export type PasswordRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/password/properties/scopes}
*/
export type PasswordScopes = (MapOfStrings);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials/properties/tokenUrl}
*/
export type ClientCredentialsTokenUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials/properties/refreshUrl}
*/
export type ClientCredentialsRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/client-credentials/properties/scopes}
*/
export type ClientCredentialsScopes = (MapOfStrings);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/authorizationUrl}
*/
export type AuthorizationCodeAuthorizationUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/tokenUrl}
*/
export type AuthorizationCodeTokenUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/refreshUrl}
*/
export type AuthorizationCodeRefreshUrl = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/oauth-flows/$defs/authorization-code/properties/scopes}
*/
export type AuthorizationCodeScopes = (MapOfStrings);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-requirement/additionalProperties/items}
*/
export type SecurityRequirementItems = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/examples/properties/examples/additionalProperties}
*/
export type ExamplesExamplesAdditionalProperties = (ExampleOrReference);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/if/properties/style}
*/
export type ExplodeDefaultStyle = ("form");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/then/properties/explode}
*/
export type EncodingExplodeDefaultExplode = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/encoding/$defs/explode-default/else/properties/explode}
*/
export type ElseExplodeDefaultExplode = (unknown);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/if/properties/type}
*/
export type TypeApikeyType = ("apiKey");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/then/properties/name}
*/
export type TypeApikeyName = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-apikey/then/properties/in}
*/
export type TypeApikeyIn = ("query" |
"header" |
"cookie");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/if/properties/type}
*/
export type TypeHttpType = ("http");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http/then/properties/scheme}
*/
export type TypeHttpScheme = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/if/properties/type}
*/
export type TypeHttpBearerType = ("http");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/if/properties/scheme}
*/
export type TypeHttpBearerScheme = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-http-bearer/then/properties/bearerFormat}
*/
export type BearerFormat = (string);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/if/properties/type}
*/
export type TypeOauth2Type = ("oauth2");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oauth2/then/properties/flows}
*/
export type Flows = (OauthFlows);
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/if/properties/type}
*/
export type TypeOidcType = ("openIdConnect");
/**
* @see {@link https://spec.openapis.org/oas/3.1/schema/2022-10-07#/$defs/security-scheme/$defs/type-oidc/then/properties/openIdConnectUrl}
*/
export type OpenIdConnectUrl = (string);
